# Usando uma imagem base do Nginx versão apline
FROM nginx:alpine

# Copiando os arquivos do projeto para o diretório de conteúdo estático do Nginx
COPY . /usr/share/nginx/html

# Expondo a porta 80
EXPOSE 80